### ISSUE TITLE
8 Substation Model - Fix Interconnections Between Control Center and Substations

### ISSUE THREAD

**Issue by cptlc** [cptlc/cptl-models#6]
There are bugs here when we merge the substation graphs with the control center network.

**Comment by cptlc** [comment]
Consider the merge we obtain when we connect a serially-connected substation to that of the control center network.  This needs fixed.

PREFIX cptlc: urn:cite:cptl:general.cptlc.2014_07:
PREFIX enet:  urn:cite:cptl:enterprise.enet.2015_07:
PREFIX rdf:   http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX rdfs:  http://www.w3.org/2000/01/rdf-schema#
PREFIX snet:  urn:cite:cptl:power.snet.2015_07:
PREFIX syard: urn:cite:cptl:power.syard.2016_07:
CONSTRUCT { ?v rdfs:label ?label .
            ?v rdf:type ?type_str .
            ?s ?p ?o . }
FROM urn:cite:cptl:power.8sub.2016_08:Control_Center.network
FROM urn:cite:cptl:power.8sub.2016_08:Haverbrook.network
FROM urn:cite:cptl:power.8sub.2016_08:Haverbrook.yard
WHERE {
?v rdfs:label ?label .
?v rdf:type ?type .
BIND ( STR(?type) AS ?type_str )
?s ?p ?o .
FILTER( sameTerm(?p, urn:cite:cptl:power.syard.2016_07:hasLine) || sameTerm(?p, urn:cite:cptl:general.cptlc.2014_07:hasEthernetLink) || sameTerm(?p, urn:cite:cptl:power.snet.2015_07:hasBreakerConnections) || sameTerm(?p, urn:cite:cptl:general.cptlc.2014_07:hasFiberEthernetLink) ||
 sameTerm(?p, urn:cite:cptl:general.cptlc.2014_07:hasSerialLink) || sameTerm(?p, urn:cite:cptl:general.cptlc.2014_07:hasComponent) || sameTerm(?p, urn:cite:cptl:enterprise.enet.2015_07:hasHost) )
}

**Comment by cptlc** [comment]
Also want to think about a clean way to look at merge at different levels of abstraction.

**Comment by gabriel-weaver** [comment]
Fixed
